name: SonarCloud Analysis

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and Test Backend
        run: |
          cd back
          mvn clean verify jacoco:report

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: |
          cd front
          npm install

      - name: Run Angular tests with coverage
        run: |
          cd front
          npm run test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage

      - name: Debug – Show generated lcov
        run: |
          ls -la front/coverage/bobapp
          head -n 10 front/coverage/bobapp/lcov.info

      - name: Fix lcov paths
        run: |
          sed -i 's|SF:.*/src|SF:src|' front/coverage/bobapp/lcov.info

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
